apiVersion: v1
items:
- apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    labels:
      kubenix/project-name: kubenix
    name: build-storage
    namespace: default
  parameters:
    blockPool: brigade-storage
    clusterNamespace: storage
  provisioner: k8s.io/minikube-hostpath
- apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    labels:
      kubenix/project-name: kubenix
    name: cache-storage
    namespace: default
  parameters:
    blockPool: brigade-cache
    clusterNamespace: storage
  provisioner: k8s.io/minikube-hostpath
kind: List
labels:
