# edit /etc/hosts and add
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: istio-system
spec:
  secretName: ingress-cert
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: dev.cluster
  dnsNames:
  - dev.cluster
  acme:
    config:
    - http01:
        ingressClass: istio
      domains:
      - dev.cluster