apiVersion: v1
items:
- apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      tekton.dev/git-0: https://bitbucket.org
    labels:
      kubenix/project-name: kubenix
    name: bitbucket-basic-auth
    namespace: default
  stringData:
    password: $BB_PASS
    username: $BB_USER
  type: kubernetes.io/basic-auth
- apiVersion: v1
  data:
    consumerKey: $BB_KEY
    consumerSecret: $BB_SECRET
  kind: Secret
  metadata:
    labels:
      kubenix/project-name: kubenix
    name: bitbucket-secret
    namespace: default
  type: Opaque
- apiVersion: v1
  data:
    tls.crt: $TLS_CERT
    tls.key: $TLS_KEY
  kind: Secret
  metadata:
    labels:
      kubenix/project-name: kubenix
    name: istio-ingressgateway-certs
    namespace: istio-system
  type: kubernetes.io/tls
kind: List
labels:
