apiVersion: v1
items:
- apiVersion: v1
  data:
    tls.cert: $TLS_CERT
    tls.key: $TLS_KEY
  kind: Secret
  metadata:
    labels:
      kubenix/project-name: kubenix
    name: istio-ingressgateway-certs
    namespace: istio-system
  type: kubernetes.io/tls
kind: List
labels:
