apiVersion: v1
items:
- apiVersion: v1
  data:
    access_key: $AWS_KEY
    secret_key: $AWS_SECRET
  kind: Secret
  metadata:
    labels:
      kubenix/project-name: kubenix
    name: aws-credentials
    namespace: dev-infra
  type: Opaque
- apiVersion: v1
  data:
    consumerKey: $BB_KEY
    consumerSecret: $BB_SECRET
  kind: Secret
  metadata:
    labels:
      kubenix/project-name: kubenix
    name: bitbucket-secret
    namespace: dev-infra
  type: Opaque
kind: List
labels:
