# TODO attach to brigade module
# TODO cluster-admin is too much - just an example
# INFO this role is required to make gitops possible
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: brigade-admin-privileges
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: brigade-worker
  namespace: brigade
