apiVersion: skaffold/v1beta13
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: dev.local/express-app
      sync:
        '*.js': ./src
      custom:
        buildCommand: ./skaffold.build.sh
        dependencies:
          paths:
            - /src
deploy:
  kubectl:
    manifests:
      - ../k8s-*