apiVersion: v1
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    labels:
      kubenix/project-name: kubenix
    name: system
    namespace: default
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app.kubernetes.io/instance: eks-cluster-autoscaler
      app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/name: aws-cluster-autoscaler
      helm.sh/chart: cluster-autoscaler-3.2.0
      kubenix/project-name: kubenix
    name: eks-cluster-autoscaler-aws-cluster-autoscaler
    namespace: system
  spec:
    ports:
    - name: http
      port: 8085
      protocol: TCP
      targetPort: 8085
    selector:
      app.kubernetes.io/instance: eks-cluster-autoscaler
      app.kubernetes.io/name: aws-cluster-autoscaler
    type: ClusterIP
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      app.kubernetes.io/instance: eks-cluster-autoscaler
      app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/name: aws-cluster-autoscaler
      helm.sh/chart: cluster-autoscaler-3.2.0
      kubenix/project-name: kubenix
    name: eks-cluster-autoscaler-aws-cluster-autoscaler
    namespace: system
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app.kubernetes.io/instance: eks-cluster-autoscaler
      app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/name: aws-cluster-autoscaler
      helm.sh/chart: cluster-autoscaler-3.2.0
      kubenix/project-name: kubenix
    name: eks-cluster-autoscaler-aws-cluster-autoscaler
    namespace: system
  spec:
    replicas: 1
    selector:
      matchLabels:
        app.kubernetes.io/instance: eks-cluster-autoscaler
        app.kubernetes.io/name: aws-cluster-autoscaler
    template:
      metadata:
        labels:
          app.kubernetes.io/instance: eks-cluster-autoscaler
          app.kubernetes.io/name: aws-cluster-autoscaler
      spec:
        containers:
        - command:
          - ./cluster-autoscaler
          - --cloud-provider=aws
          - --namespace=system
          - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/future-is-comming-cluster
          - --logtostderr=true
          - --stderrthreshold=info
          - --v=4
          env:
          - name: AWS_REGION
            value: eu-west-2
          image: k8s.gcr.io/cluster-autoscaler:v1.13.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health-check
              port: 8085
          name: aws-cluster-autoscaler
          ports:
          - containerPort: 8085
          resources: {}
          volumeMounts:
          - mountPath: /etc/ssl/certs/ca-bundle.crt
            name: ssl-certs
            readOnly: true
        nodeSelector:
          kubernetes.io/lifecycle: dedicated
        serviceAccountName: eks-cluster-autoscaler-aws-cluster-autoscaler
        tolerations: []
        volumes:
        - hostPath:
            path: /etc/ssl/certs/ca-certificates.crt
          name: ssl-certs
- apiVersion: policy/v1beta1
  kind: PodDisruptionBudget
  metadata:
    labels:
      app.kubernetes.io/instance: eks-cluster-autoscaler
      app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/name: aws-cluster-autoscaler
      helm.sh/chart: cluster-autoscaler-3.2.0
      kubenix/project-name: kubenix
    name: eks-cluster-autoscaler-aws-cluster-autoscaler
    namespace: system
  spec:
    maxUnavailable: 1
    selector:
      matchLabels:
        app.kubernetes.io/instance: eks-cluster-autoscaler
        app.kubernetes.io/name: aws-cluster-autoscaler
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRole
  metadata:
    labels:
      app.kubernetes.io/instance: eks-cluster-autoscaler
      app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/name: aws-cluster-autoscaler
      helm.sh/chart: cluster-autoscaler-3.2.0
      kubenix/project-name: kubenix
    name: eks-cluster-autoscaler-aws-cluster-autoscaler
    namespace: system
  rules:
  - apiGroups:
    - ''
    resources:
    - events
    - endpoints
    verbs:
    - create
    - patch
  - apiGroups:
    - ''
    resources:
    - pods/eviction
    verbs:
    - create
  - apiGroups:
    - ''
    resources:
    - pods/status
    verbs:
    - update
  - apiGroups:
    - ''
    resourceNames:
    - cluster-autoscaler
    resources:
    - endpoints
    verbs:
    - get
    - update
  - apiGroups:
    - ''
    resources:
    - nodes
    verbs:
    - watch
    - list
    - get
    - update
  - apiGroups:
    - ''
    resources:
    - pods
    - services
    - replicationcontrollers
    - persistentvolumeclaims
    - persistentvolumes
    verbs:
    - watch
    - list
    - get
  - apiGroups:
    - batch
    resources:
    - jobs
    - cronjobs
    verbs:
    - watch
    - list
    - get
  - apiGroups:
    - extensions
    resources:
    - replicasets
    - daemonsets
    verbs:
    - watch
    - list
    - get
  - apiGroups:
    - policy
    resources:
    - poddisruptionbudgets
    verbs:
    - watch
    - list
  - apiGroups:
    - apps
    resources:
    - daemonsets
    - replicasets
    - statefulsets
    verbs:
    - watch
    - list
    - get
  - apiGroups:
    - storage.k8s.io
    resources:
    - storageclasses
    verbs:
    - watch
    - list
    - get
  - apiGroups:
    - ''
    resources:
    - configmaps
    verbs:
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRoleBinding
  metadata:
    labels:
      app.kubernetes.io/instance: eks-cluster-autoscaler
      app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/name: aws-cluster-autoscaler
      helm.sh/chart: cluster-autoscaler-3.2.0
      kubenix/project-name: kubenix
    name: eks-cluster-autoscaler-aws-cluster-autoscaler
    namespace: system
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: eks-cluster-autoscaler-aws-cluster-autoscaler
  subjects:
  - kind: ServiceAccount
    name: eks-cluster-autoscaler-aws-cluster-autoscaler
    namespace: system
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: Role
  metadata:
    labels:
      app.kubernetes.io/instance: eks-cluster-autoscaler
      app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/name: aws-cluster-autoscaler
      helm.sh/chart: cluster-autoscaler-3.2.0
      kubenix/project-name: kubenix
    name: eks-cluster-autoscaler-aws-cluster-autoscaler
    namespace: system
  rules:
  - apiGroups:
    - ''
    resources:
    - configmaps
    verbs:
    - create
  - apiGroups:
    - ''
    resourceNames:
    - cluster-autoscaler-status
    resources:
    - configmaps
    verbs:
    - delete
    - get
    - update
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: RoleBinding
  metadata:
    labels:
      app.kubernetes.io/instance: eks-cluster-autoscaler
      app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/name: aws-cluster-autoscaler
      helm.sh/chart: cluster-autoscaler-3.2.0
      kubenix/project-name: kubenix
    name: eks-cluster-autoscaler-aws-cluster-autoscaler
    namespace: system
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: eks-cluster-autoscaler-aws-cluster-autoscaler
  subjects:
  - kind: ServiceAccount
    name: eks-cluster-autoscaler-aws-cluster-autoscaler
    namespace: system
kind: List
labels:
