apiVersion: v1
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    labels:
      kubenix/project-name: kubenix
    name: system
    namespace: default
- apiVersion: apps/v1beta2
  kind: Deployment
  metadata:
    annotations: {}
    labels:
      app: efs-provisioner
      chart: efs-provisioner-0.7.0
      env: dev
      heritage: Tiller
      kubenix/project-name: kubenix
      release: efs-provisioner
    name: efs-provisioner
    namespace: system
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: efs-provisioner
        release: efs-provisioner
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: efs-provisioner
          release: efs-provisioner
      spec:
        containers:
        - env:
          - name: AWS_REGION
            value: eu-west-2
          - name: FILE_SYSTEM_ID
            value: $patch_required
          - name: PROVISIONER_NAME
            value: kubernetes.io/aws-efs
          image: quay.io/external_storage/efs-provisioner:v2.2.0-k8s1.12
          imagePullPolicy: IfNotPresent
          name: efs-provisioner
          resources: {}
          volumeMounts:
          - mountPath: /persistentvolumes
            name: pv-volume
        serviceAccount: efs-provisioner
        volumes:
        - name: pv-volume
          nfs:
            path: /
            server: $patch_required.efs.eu-west-2.amazonaws.com
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app.kubernetes.io/instance: eks-cluster-autoscaler
      app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/name: aws-cluster-autoscaler
      helm.sh/chart: cluster-autoscaler-3.2.0
      kubenix/project-name: kubenix
    name: eks-cluster-autoscaler-aws-cluster-autoscaler
    namespace: system
  spec:
    ports:
    - name: http
      port: 8085
      protocol: TCP
      targetPort: 8085
    selector:
      app.kubernetes.io/instance: eks-cluster-autoscaler
      app.kubernetes.io/name: aws-cluster-autoscaler
    type: ClusterIP
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations: {}
    labels:
      app: efs-provisioner
      chart: efs-provisioner-0.7.0
      env: dev
      heritage: Tiller
      kubenix/project-name: kubenix
      release: efs-provisioner
    name: efs-provisioner
    namespace: system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      app.kubernetes.io/instance: eks-cluster-autoscaler
      app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/name: aws-cluster-autoscaler
      helm.sh/chart: cluster-autoscaler-3.2.0
      kubenix/project-name: kubenix
    name: eks-cluster-autoscaler-aws-cluster-autoscaler
    namespace: system
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app.kubernetes.io/instance: eks-cluster-autoscaler
      app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/name: aws-cluster-autoscaler
      helm.sh/chart: cluster-autoscaler-3.2.0
      kubenix/project-name: kubenix
    name: eks-cluster-autoscaler-aws-cluster-autoscaler
    namespace: system
  spec:
    replicas: 1
    selector:
      matchLabels:
        app.kubernetes.io/instance: eks-cluster-autoscaler
        app.kubernetes.io/name: aws-cluster-autoscaler
    template:
      metadata:
        labels:
          app.kubernetes.io/instance: eks-cluster-autoscaler
          app.kubernetes.io/name: aws-cluster-autoscaler
      spec:
        containers:
        - command:
          - ./cluster-autoscaler
          - --cloud-provider=aws
          - --namespace=system
          - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/future-is-comming-cluster
          - --logtostderr=true
          - --stderrthreshold=info
          - --v=4
          env:
          - name: AWS_REGION
            value: eu-west-2
          image: k8s.gcr.io/cluster-autoscaler:v1.13.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health-check
              port: 8085
          name: aws-cluster-autoscaler
          ports:
          - containerPort: 8085
          resources: {}
          volumeMounts:
          - mountPath: /etc/ssl/certs/ca-bundle.crt
            name: ssl-certs
            readOnly: true
        nodeSelector:
          kubernetes.io/lifecycle: on-demand
        serviceAccountName: eks-cluster-autoscaler-aws-cluster-autoscaler
        tolerations: []
        volumes:
        - hostPath:
            path: /etc/ssl/certs/ca-certificates.crt
          name: ssl-certs
- apiVersion: policy/v1beta1
  kind: PodDisruptionBudget
  metadata:
    labels:
      app.kubernetes.io/instance: eks-cluster-autoscaler
      app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/name: aws-cluster-autoscaler
      helm.sh/chart: cluster-autoscaler-3.2.0
      kubenix/project-name: kubenix
    name: eks-cluster-autoscaler-aws-cluster-autoscaler
    namespace: system
  spec:
    maxUnavailable: 1
    selector:
      matchLabels:
        app.kubernetes.io/instance: eks-cluster-autoscaler
        app.kubernetes.io/name: aws-cluster-autoscaler
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    annotations: {}
    labels:
      app: efs-provisioner
      chart: efs-provisioner-0.7.0
      env: dev
      heritage: Tiller
      kubenix/project-name: kubenix
      release: efs-provisioner
    name: efs-provisioner
    namespace: system
  rules:
  - apiGroups:
    - ''
    resources:
    - persistentvolumes
    verbs:
    - get
    - list
    - watch
    - create
    - delete
  - apiGroups:
    - ''
    resources:
    - persistentvolumeclaims
    verbs:
    - get
    - list
    - watch
    - update
  - apiGroups:
    - storage.k8s.io
    resources:
    - storageclasses
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ''
    resources:
    - events
    verbs:
    - list
    - watch
    - create
    - update
    - patch
  - apiGroups:
    - ''
    resources:
    - endpoints
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    annotations: {}
    labels:
      app: efs-provisioner
      chart: efs-provisioner-0.7.0
      env: dev
      heritage: Tiller
      kubenix/project-name: kubenix
      release: efs-provisioner
    name: efs-provisioner
    namespace: system
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: efs-provisioner
  subjects:
  - kind: ServiceAccount
    name: efs-provisioner
    namespace: system
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRole
  metadata:
    labels:
      app.kubernetes.io/instance: eks-cluster-autoscaler
      app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/name: aws-cluster-autoscaler
      helm.sh/chart: cluster-autoscaler-3.2.0
      kubenix/project-name: kubenix
    name: eks-cluster-autoscaler-aws-cluster-autoscaler
    namespace: system
  rules:
  - apiGroups:
    - ''
    resources:
    - events
    - endpoints
    verbs:
    - create
    - patch
  - apiGroups:
    - ''
    resources:
    - pods/eviction
    verbs:
    - create
  - apiGroups:
    - ''
    resources:
    - pods/status
    verbs:
    - update
  - apiGroups:
    - ''
    resourceNames:
    - cluster-autoscaler
    resources:
    - endpoints
    verbs:
    - get
    - update
  - apiGroups:
    - ''
    resources:
    - nodes
    verbs:
    - watch
    - list
    - get
    - update
  - apiGroups:
    - ''
    resources:
    - pods
    - services
    - replicationcontrollers
    - persistentvolumeclaims
    - persistentvolumes
    verbs:
    - watch
    - list
    - get
  - apiGroups:
    - batch
    resources:
    - jobs
    - cronjobs
    verbs:
    - watch
    - list
    - get
  - apiGroups:
    - extensions
    resources:
    - replicasets
    - daemonsets
    verbs:
    - watch
    - list
    - get
  - apiGroups:
    - policy
    resources:
    - poddisruptionbudgets
    verbs:
    - watch
    - list
  - apiGroups:
    - apps
    resources:
    - daemonsets
    - replicasets
    - statefulsets
    verbs:
    - watch
    - list
    - get
  - apiGroups:
    - storage.k8s.io
    resources:
    - storageclasses
    verbs:
    - watch
    - list
    - get
  - apiGroups:
    - ''
    resources:
    - configmaps
    verbs:
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRoleBinding
  metadata:
    labels:
      app.kubernetes.io/instance: eks-cluster-autoscaler
      app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/name: aws-cluster-autoscaler
      helm.sh/chart: cluster-autoscaler-3.2.0
      kubenix/project-name: kubenix
    name: eks-cluster-autoscaler-aws-cluster-autoscaler
    namespace: system
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: eks-cluster-autoscaler-aws-cluster-autoscaler
  subjects:
  - kind: ServiceAccount
    name: eks-cluster-autoscaler-aws-cluster-autoscaler
    namespace: system
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: Role
  metadata:
    labels:
      app.kubernetes.io/instance: eks-cluster-autoscaler
      app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/name: aws-cluster-autoscaler
      helm.sh/chart: cluster-autoscaler-3.2.0
      kubenix/project-name: kubenix
    name: eks-cluster-autoscaler-aws-cluster-autoscaler
    namespace: system
  rules:
  - apiGroups:
    - ''
    resources:
    - configmaps
    verbs:
    - create
  - apiGroups:
    - ''
    resourceNames:
    - cluster-autoscaler-status
    resources:
    - configmaps
    verbs:
    - delete
    - get
    - update
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: RoleBinding
  metadata:
    labels:
      app.kubernetes.io/instance: eks-cluster-autoscaler
      app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/name: aws-cluster-autoscaler
      helm.sh/chart: cluster-autoscaler-3.2.0
      kubenix/project-name: kubenix
    name: eks-cluster-autoscaler-aws-cluster-autoscaler
    namespace: system
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: eks-cluster-autoscaler-aws-cluster-autoscaler
  subjects:
  - kind: ServiceAccount
    name: eks-cluster-autoscaler-aws-cluster-autoscaler
    namespace: system
- apiVersion: storage.k8s.io/v1beta1
  kind: StorageClass
  metadata:
    labels:
      app: efs-provisioner
      chart: efs-provisioner-0.7.0
      env: dev
      heritage: Tiller
      kubenix/project-name: kubenix
      release: efs-provisioner
    name: efs
    namespace: system
  parameters:
    gidAllocate: 'true'
    gidMax: '50000'
    gidMin: '40000'
  provisioner: kubernetes.io/aws-efs
  reclaimPolicy: Delete
kind: List
labels:
