apiVersion: v1
items:
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    labels:
      kubenix/project-name: kubenix
    name: cephblockpools.ceph.rook.io
    namespace: storage
  spec:
    group: ceph.rook.io
    names:
      kind: CephBlockPool
      listKind: CephBlockPoolList
      plural: cephblockpools
      singular: cephblockpool
    scope: Namespaced
    version: v1
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    labels:
      kubenix/project-name: kubenix
    name: cephclusters.ceph.rook.io
    namespace: storage
  spec:
    additionalPrinterColumns:
    - JSONPath: .spec.dataDirHostPath
      description: Directory used on the K8s nodes
      name: DataDirHostPath
      type: string
    - JSONPath: .spec.mon.count
      description: Number of MONs
      name: MonCount
      type: string
    - JSONPath: .metadata.creationTimestamp
      name: Age
      type: date
    - JSONPath: .status.state
      description: Current State
      name: State
      type: string
    group: ceph.rook.io
    names:
      kind: CephCluster
      listKind: CephClusterList
      plural: cephclusters
      singular: cephcluster
    scope: Namespaced
    validation:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              cephVersion:
                properties:
                  allowUnsupported:
                    type: boolean
                  image:
                    type: string
                  name:
                    pattern: ^(luminous|mimic|nautilus)$
                    type: string
              dashboard:
                properties:
                  enabled:
                    type: boolean
                  port:
                    maximum: 65535
                    minimum: 0
                    type: integer
                  urlPrefix:
                    type: string
              dataDirHostPath:
                pattern: ^/(\S+)
                type: string
              mon:
                properties:
                  allowMultiplePerNode:
                    type: boolean
                  count:
                    maximum: 9
                    minimum: 1
                    type: integer
                required:
                - count
              network:
                properties:
                  hostNetwork:
                    type: boolean
              storage:
                properties:
                  nodes:
                    items: {}
                    type: array
                  useAllDevices: {}
                  useAllNodes:
                    type: boolean
            required:
            - mon
    version: v1
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    labels:
      kubenix/project-name: kubenix
    name: cephfilesystems.ceph.rook.io
    namespace: storage
  spec:
    additionalPrinterColumns:
    - JSONPath: .spec.metadataServer.activeCount
      description: Number of MDSs
      name: MdsCount
      type: string
    - JSONPath: .metadata.creationTimestamp
      name: Age
      type: date
    group: ceph.rook.io
    names:
      kind: CephFilesystem
      listKind: CephFilesystemList
      plural: cephfilesystems
      singular: cephfilesystem
    scope: Namespaced
    version: v1
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    labels:
      kubenix/project-name: kubenix
    name: cephnfses.ceph.rook.io
    namespace: storage
  spec:
    group: ceph.rook.io
    names:
      kind: CephNFS
      listKind: CephNFSList
      plural: cephnfses
      shortNames:
      - nfs
      singular: cephnfs
    scope: Namespaced
    version: v1
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    labels:
      kubenix/project-name: kubenix
    name: cephobjectstores.ceph.rook.io
    namespace: storage
  spec:
    group: ceph.rook.io
    names:
      kind: CephObjectStore
      listKind: CephObjectStoreList
      plural: cephobjectstores
      singular: cephobjectstore
    scope: Namespaced
    version: v1
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    labels:
      kubenix/project-name: kubenix
    name: cephobjectstoreusers.ceph.rook.io
    namespace: storage
  spec:
    group: ceph.rook.io
    names:
      kind: CephObjectStoreUser
      listKind: CephObjectStoreUserList
      plural: cephobjectstoreusers
      shortNames:
      - rcou
      - objectuser
      singular: cephobjectstoreuser
    scope: Namespaced
    version: v1
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    labels:
      kubenix/project-name: kubenix
    name: volumes.rook.io
    namespace: storage
  spec:
    group: rook.io
    names:
      kind: Volume
      listKind: VolumeList
      plural: volumes
      shortNames:
      - rv
      singular: volume
    scope: Namespaced
    version: v1alpha2
- apiVersion: v1
  kind: Namespace
  metadata:
    labels:
      kubenix/project-name: kubenix
    name: storage
    namespace: default
- apiVersion: ceph.rook.io/v1
  kind: CephCluster
  metadata:
    labels:
      kubenix/project-name: kubenix
    name: rook-ceph
    namespace: storage
  spec:
    cephVersion:
      image: ceph/ceph:v14.2
    dashboard:
      enabled: true
      port: 8443
      ssl: false
    dataDirHostPath: /var/lib/rook
    mon:
      allowMultiplePerNode: true
      count: 2
    storage:
      config:
        storeType: filestore
      directories:
      - path: /var/lib/rook
      useAllDevices: false
      useAllNodes: true
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      chart: rook-ceph-v1.0.5
      kubenix/project-name: kubenix
      operator: rook
      storage-backend: ceph
    name: rook-ceph-operator
    namespace: storage
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: rook-ceph-operator
    template:
      metadata:
        labels:
          app: rook-ceph-operator
          chart: rook-ceph-v1.0.5
      spec:
        containers:
        - args:
          - ceph
          - operator
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: ROOK_CEPH_STATUS_CHECK_INTERVAL
            value: 60s
          - name: ROOK_CURRENT_NAMESPACE_ONLY
            value: 'true'
          - name: ROOK_ENABLE_SELINUX_RELABELING
            value: 'true'
          - name: ROOK_LOG_LEVEL
            value: INFO
          - name: ROOK_MON_HEALTHCHECK_INTERVAL
            value: 45s
          - name: ROOK_MON_OUT_TIMEOUT
            value: 600s
          image: rook/ceph:v1.0.5
          imagePullPolicy: IfNotPresent
          name: rook-ceph-operator
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
        serviceAccountName: rook-ceph-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      chart: rook-ceph-v1.0.5
      kubenix/project-name: kubenix
      operator: rook
      storage-backend: ceph
    name: rook-ceph-mgr
    namespace: storage
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      chart: rook-ceph-v1.0.5
      kubenix/project-name: kubenix
      operator: rook
      storage-backend: ceph
    name: rook-ceph-osd
    namespace: storage
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      chart: rook-ceph-v1.0.5
      kubenix/project-name: kubenix
      operator: rook
      storage-backend: ceph
    name: rook-ceph-system
    namespace: storage
- apiVersion: policy/v1beta1
  kind: PodSecurityPolicy
  metadata:
    labels:
      kubenix/project-name: kubenix
    name: 00-rook-ceph-operator
    namespace: storage
  spec:
    allowedCapabilities:
    - '*'
    fsGroup:
      rule: RunAsAny
    hostIPC: true
    hostNetwork: true
    hostPID: true
    privileged: true
    runAsUser:
      rule: RunAsAny
    seLinux:
      rule: RunAsAny
    supplementalGroups:
      rule: RunAsAny
    volumes:
    - '*'
- aggregationRule:
    clusterRoleSelectors:
    - matchLabels:
        rbac.rook.ceph.io/aggregate-to-rook-ceph-cluster-mgmt: 'true'
  apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRole
  metadata:
    labels:
      kubenix/project-name: kubenix
      operator: rook
      storage-backend: ceph
    name: rook-ceph-cluster-mgmt
    namespace: storage
  rules: []
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRole
  metadata:
    labels:
      kubenix/project-name: kubenix
      operator: rook
      rbac.rook.ceph.io/aggregate-to-rook-ceph-cluster-mgmt: 'true'
      storage-backend: ceph
    name: rook-ceph-cluster-mgmt-rules
    namespace: storage
  rules:
  - apiGroups:
    - ''
    resources:
    - secrets
    - pods
    - pods/log
    - services
    - configmaps
    verbs:
    - get
    - list
    - watch
    - patch
    - create
    - update
    - delete
  - apiGroups:
    - apps
    resources:
    - deployments
    - daemonsets
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
- aggregationRule:
    clusterRoleSelectors:
    - matchLabels:
        rbac.ceph.rook.io/aggregate-to-rook-ceph-global: 'true'
  apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRole
  metadata:
    labels:
      kubenix/project-name: kubenix
      operator: rook
      storage-backend: ceph
    name: rook-ceph-global
    namespace: storage
  rules: []
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRole
  metadata:
    labels:
      kubenix/project-name: kubenix
      operator: rook
      rbac.ceph.rook.io/aggregate-to-rook-ceph-global: 'true'
      storage-backend: ceph
    name: rook-ceph-global-rules
    namespace: storage
  rules:
  - apiGroups:
    - ''
    resources:
    - pods
    - nodes
    - nodes/proxy
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ''
    resources:
    - events
    - persistentvolumes
    - persistentvolumeclaims
    - endpoints
    verbs:
    - get
    - list
    - watch
    - patch
    - create
    - update
    - delete
  - apiGroups:
    - storage.k8s.io
    resources:
    - storageclasses
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - batch
    resources:
    - jobs
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
  - apiGroups:
    - ceph.rook.io
    resources:
    - '*'
    verbs:
    - '*'
  - apiGroups:
    - rook.io
    resources:
    - '*'
    verbs:
    - '*'
- aggregationRule:
    clusterRoleSelectors:
    - matchLabels:
        rbac.ceph.rook.io/aggregate-to-rook-ceph-mgr-cluster: 'true'
  apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRole
  metadata:
    labels:
      kubenix/project-name: kubenix
      operator: rook
      storage-backend: ceph
    name: rook-ceph-mgr-cluster
    namespace: storage
  rules: []
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRole
  metadata:
    labels:
      kubenix/project-name: kubenix
      operator: rook
      rbac.ceph.rook.io/aggregate-to-rook-ceph-mgr-cluster: 'true'
      storage-backend: ceph
    name: rook-ceph-mgr-cluster-rules
    namespace: storage
  rules:
  - apiGroups:
    - ''
    resources:
    - configmaps
    - nodes
    - nodes/proxy
    verbs:
    - get
    - list
    - watch
- aggregationRule:
    clusterRoleSelectors:
    - matchLabels:
        rbac.ceph.rook.io/aggregate-to-rook-ceph-mgr-system: 'true'
  apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRole
  metadata:
    labels:
      kubenix/project-name: kubenix
    name: rook-ceph-mgr-system
    namespace: storage
  rules: []
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRole
  metadata:
    labels:
      kubenix/project-name: kubenix
      rbac.ceph.rook.io/aggregate-to-rook-ceph-mgr-system: 'true'
    name: rook-ceph-mgr-system-rules
    namespace: storage
  rules:
  - apiGroups:
    - ''
    resources:
    - configmaps
    verbs:
    - get
    - list
    - watch
- aggregationRule:
    clusterRoleSelectors:
    - matchLabels:
        rbac.ceph.rook.io/aggregate-to-rook-ceph-system-psp-user: 'true'
  apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRole
  metadata:
    labels:
      chart: rook-ceph-v1.0.5
      kubenix/project-name: kubenix
      operator: rook
      storage-backend: ceph
    name: rook-ceph-system-psp-user
    namespace: storage
  rules: []
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRole
  metadata:
    labels:
      chart: rook-ceph-v1.0.5
      kubenix/project-name: kubenix
      operator: rook
      rbac.ceph.rook.io/aggregate-to-rook-ceph-system-psp-user: 'true'
      storage-backend: ceph
    name: rook-ceph-system-psp-user-rules
    namespace: storage
  rules:
  - apiGroups:
    - apps
    resourceNames:
    - 00-rook-ceph-operator
    resources:
    - podsecuritypolicies
    verbs:
    - use
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRoleBinding
  metadata:
    labels:
      chart: rook-ceph-v1.0.5
      kubenix/project-name: kubenix
      operator: rook
      storage-backend: ceph
    name: rook-ceph-global
    namespace: storage
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: rook-ceph-global
  subjects:
  - kind: ServiceAccount
    name: rook-ceph-system
    namespace: storage
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRoleBinding
  metadata:
    labels:
      kubenix/project-name: kubenix
    name: rook-ceph-mgr-cluster
    namespace: storage
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: rook-ceph-mgr-cluster
  subjects:
  - kind: ServiceAccount
    name: rook-ceph-mgr
    namespace: storage
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRoleBinding
  metadata:
    labels:
      chart: rook-ceph-v1.0.5
      kubenix/project-name: kubenix
      operator: rook
      storage-backend: ceph
    name: rook-ceph-system-psp-users
    namespace: storage
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: rook-ceph-system-psp-user
  subjects:
  - kind: ServiceAccount
    name: rook-ceph-system
    namespace: storage
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: Role
  metadata:
    labels:
      kubenix/project-name: kubenix
    name: rook-ceph-mgr
    namespace: storage
  rules:
  - apiGroups:
    - ''
    resources:
    - pods
    - services
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - batch
    resources:
    - jobs
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
  - apiGroups:
    - ceph.rook.io
    resources:
    - '*'
    verbs:
    - '*'
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: Role
  metadata:
    labels:
      kubenix/project-name: kubenix
    name: rook-ceph-osd
    namespace: storage
  rules:
  - apiGroups:
    - ''
    resources:
    - configmaps
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: Role
  metadata:
    labels:
      kubenix/project-name: kubenix
      operator: rook
      storage-backend: ceph
    name: rook-ceph-system
    namespace: storage
  rules:
  - apiGroups:
    - ''
    resources:
    - pods
    - configmaps
    - services
    verbs:
    - get
    - list
    - watch
    - patch
    - create
    - update
    - delete
  - apiGroups:
    - apps
    resources:
    - daemonsets
    - statefulsets
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: RoleBinding
  metadata:
    labels:
      kubenix/project-name: kubenix
    name: rook-ceph-cluster-mgmt
    namespace: storage
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: rook-ceph-cluster-mgmt
  subjects:
  - kind: ServiceAccount
    name: rook-ceph-system
    namespace: storage
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: RoleBinding
  metadata:
    labels:
      kubenix/project-name: kubenix
    name: rook-ceph-mgr
    namespace: storage
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: rook-ceph-mgr
  subjects:
  - kind: ServiceAccount
    name: rook-ceph-mgr
    namespace: storage
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: RoleBinding
  metadata:
    labels:
      kubenix/project-name: kubenix
    name: rook-ceph-mgr-system
    namespace: storage
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: rook-ceph-mgr-system
  subjects:
  - kind: ServiceAccount
    name: rook-ceph-mgr
    namespace: storage
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: RoleBinding
  metadata:
    labels:
      kubenix/project-name: kubenix
    name: rook-ceph-osd
    namespace: storage
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: rook-ceph-osd
  subjects:
  - kind: ServiceAccount
    name: rook-ceph-osd
    namespace: storage
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: RoleBinding
  metadata:
    labels:
      kubenix/project-name: kubenix
      operator: rook
      storage-backend: ceph
    name: rook-ceph-system
    namespace: storage
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: rook-ceph-system
  subjects:
  - kind: ServiceAccount
    name: rook-ceph-system
    namespace: storage
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: rook-ceph-tools
    name: rook-ceph-tools
    namespace: storage
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: rook-ceph-tools
    template:
      metadata:
        labels:
          app: rook-ceph-tools
      spec:
        containers:
        - args:
          - -g
          - --
          - /usr/local/bin/toolbox.sh
          command:
          - /tini
          env:
          - name: ROOK_ADMIN_SECRET
            valueFrom:
              secretKeyRef:
                key: admin-secret
                name: rook-ceph-mon
          image: rook/ceph:v1.0.5
          imagePullPolicy: IfNotPresent
          name: rook-ceph-tools
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /dev
            name: dev
          - mountPath: /sys/bus
            name: sysbus
          - mountPath: /lib/modules
            name: libmodules
          - mountPath: /etc/rook
            name: mon-endpoint-volume
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        volumes:
        - hostPath:
            path: /dev
          name: dev
        - hostPath:
            path: /sys/bus
          name: sysbus
        - hostPath:
            path: /lib/modules
          name: libmodules
        - configMap:
            items:
            - key: data
              path: mon-endpoints
            name: rook-ceph-mon-endpoints
          name: mon-endpoint-volume
kind: List
labels:
