apiVersion: v1
items:
- apiVersion: v1
  data:
    access_key: $AWS_KEY
    secret_key: $AWS_SECRET
  kind: Secret
  metadata:
    labels:
      kubenix/project-name: kubenix
    name: aws-credentials
    namespace: brigade
  type: Opaque
kind: List
labels:
