apiVersion: v1
items:
- apiVersion: v1
  data:
    access-key: ''
    secret-key: ''
  kind: Secret
  metadata:
    labels:
      kubenix/project-name: kubenix
    name: aws-secret
    namespace: default
  type: Opaque
kind: List
labels:
