apiVersion: v1
items:
- apiVersion: v1
  data:
    dev.cluster: ''
  kind: ConfigMap
  metadata:
    labels:
      kubenix/project-name: kubenix
    name: config-domain
    namespace: knative-serving
- apiVersion: serving.knative.dev/v1alpha1
  kind: Service
  metadata:
    labels:
      kubenix/project-name: kubenix
    name: express-app
    namespace: functions
  spec:
    template:
      metadata:
        annotations:
          autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
          autoscaling.knative.dev/maxScale: '100'
          autoscaling.knative.dev/metric: concurrency
          autoscaling.knative.dev/target: '5'
      spec:
        containers:
        - env:
          - name: TARGET
            value: Node.js Sample v1
          image: dev.local/express-app:dev-build
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              path: /healthz
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            requests:
              cpu: 100m
kind: List
labels:
