# brigade cache snapshoter
# move to brigade
# FIXME https://github.com/xtruder/kubenix/commit/5e292298792863f6ac72e94f5511e6ea3137594c#diff-c5105c2ed72f03d3e3c3a93e85cf6574R26
# kubernetes.imports = [
#     ./pod.json
#     ./deployment.yaml
#   ];
kind: Pod
apiVersion: v1
metadata:
  name: volume-debugger
  # namespace: ci
  annotations:
    backup.velero.io/backup-volumes: volume-to-debug
spec:
  volumes:
    # - name: volume-to-debug
    #   persistentVolumeClaim:
    #     claimName: embracing-nix-docker-k8s-helm-knative-test
    - name: volume-to-debug
      persistentVolumeClaim:
        claimName: nixos
  containers:
    - name: debugger
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - mountPath: "/data"
          name: volume-to-debug
