apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  # namespace: rook-ceph
  namespace: system
spec:
  cephVersion:
    # For the latest ceph images, see https://hub.docker.com/r/ceph/ceph/tags
    image: ceph/ceph:v14.2
  dataDirHostPath: /var/lib/rook
  mon:
    allowMultiplePerNode: true
    count: 2
  dashboard:
    enabled: true
    port: 8443
    ssl: false
  storage:
    useAllNodes: true
    useAllDevices: false
    # Important: Directories should only be used in pre-production environments
    directories:
    - path: /var/lib/rook
    config:
      storeType: filestore
    # placement:
    #   all:
    #     nodeAffinity:
    #       requiredDuringSchedulingIgnoredDuringExecution:
    #         nodeSelectorTerms:
    #         - matchExpressions:
    #           - key: rook-edgefs
    #             operator: In
    #             values:
    #             - cluster
    #     tolerations:
    #     - key: rook-edgefs
    #       operator: Exists
      mgr:
        nodeAffinity:
        tolerations:
      mon:
        nodeAffinity:
        tolerations:
      osd:
        nodeAffinity:
        tolerations: