############################################################
# OPA admission control policy for injecting policy.
############################################################
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: policy
  name: inject-policy
data:
  inject.rego: |
    package istio
    inject = {
      "apiVersion": "admission.k8s.io/v1beta1",
      "kind": "AdmissionReview",
      "response": {
        "allowed": true,
        "patchType": "JSONPatch",
        "patch": base64url.encode(json.marshal(patch)),
      },
    }
    patch = [{
      "op": "add",
      "path": "/spec/containers/-",
      "value": opa_container,
    }, {
      "op": "add",
      "path": "/spec/volumes/-",
      "value": opa_config_volume,
    }, {
      "op": "add",
      "path": "/spec/volumes/-",
      "value": opa_policy_volume,
    }]
    opa_container = {
      "image": "openpolicyagent/opa:0.13.5-istio",
      "name": "policy",
      "args": [
        "--plugin-dir=.",
        "run",
        "--server",
        "--config-file=/config/config.yaml",
        "/policy/policy.rego",
      ],
      "volumeMounts": [{
        "mountPath": "/config",
        "name": "policy-config",
      }, {
        "mountPath": "/policy",
        "name": "opa-policy",
      }],
    }
    opa_config_volume = {
      "name": "policy-config",
      "configMap": {"name": "policy-config"},
    }
    opa_policy_volume = {
      "name": "opa-policy",
      "configMap": {"name": "opa-policy"},
    }
