############################################################
# Example configuration to bootstrap policy sidecars.
############################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: policy-config
data:
  config.yaml: |
    plugins:
      envoy_ext_authz_grpc:
        addr: :9191
        query: data.istio.authz.allow
