############################################################
# Example policy to enforce into OPA-Istio sidecars.
############################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-policy
data:
  policy.rego: |
    package istio.authz
    import input.attributes.request.http as http_request
    default allow = false
    allow {
        roles_for_user[r]
        required_roles[r]
    }
    roles_for_user[r] {
        r := user_roles[user_name][_]
    }
    required_roles[r] {
        perm := role_perms[r][_]
        perm.method = http_request.method
        perm.path = http_request.path
    }
    user_name = parsed {
        [_, encoded] := split(http_request.headers.authorization, " ")
        [parsed, _] := split(base64url.decode(encoded), ":")
    }
    user_roles = {
        "alice": ["guest"],
        "bob": ["admin"]
    }
    role_perms = {
        "admin": [
            {"method": "GET",  "path": "/"},
        ],
    }
    # role_perms = {
    #     # "guest": [
    #     #     {"method": "GET",  "path": "/productpage"},
    #     # ],
    #     "admin": [
    #         {"method": "GET",  "path": "/productpage"},
    #         {"method": "GET",  "path": "/api/v1/products"},
    #     ],
    # }
