# Default values for strimzi-kafka-operator.

watchNamespaces: []
watchAnyNamespace: true

image:
  repository: strimzi
  name: operator
  tag: 0.16.2
logLevel: INFO
fullReconciliationIntervalMs: 120000
operationTimeoutMs: 300000
kubernetesServiceDnsDomain: cluster.local

tolerations: []
affinity: {}
nodeSelector: {}


# Docker images that operator uses to provision various components of Strimzi.  To use your own registry prefix the
# repository name with your registry URL.
# Ex) repository: registry.xyzcorp.com/strimzi/zookeeper
resources:
  limits:
    memory: 256Mi
    cpu: 1000m
  requests:
    memory: 256Mi
    cpu: 200m
livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 30
readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 30

# Override the docker image repository used by all Strimzi images
# imageRepositoryOverride: foobar
# Override the docker image tag used by all Strimzi images
# imageTagOverride: latest
createGlobalResources: true

