# https://eksworkshop.com/scaling/deploy_hpa/
{ 
  config, 
  pkgs,
  lib, 
  kubenix, 
  k8s-resources ? pkgs.k8s-resources,
  project-config,
  ... 
}:
let
  namespace = project-config.kubernetes.namespace;
  eks-ns = "eks";
  kn-serving = namespace.knative-serving;
  istio-ns = namespace.istio;
  functions-ns = namespace.functions;
in
{
  imports = with kubenix.modules; [ 
    # not the best flexibility - this will be included in the same yaml file
    # however it is overriding so make sense - better would be eks-service-mesh and separate file?
    istio-service-mesh
    k8s-extension
  ];

  kubernetes.imports = [
  ];

  module.scripts = [
    (pkgs.writeShellScriptBin "get-istio-ingress-lb-port" ''
      ${pkgs.kubectl}/bin/kubectl -n istio-system \
        get service istio-ingressgateway \
        -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
    '')

    # FIXME - wip
    # The certificate is at "./autogenerated.pem" and the key at "./autogenerated-key.pem" ✅
    # TODO get all functions and create cert based on that
    (pkgs.writeShellScriptBin "patch-knative-nip-domain" ''
      ${pkgs.lib.log.important "Patching knative domain"}
      ${pkgs.lib.log.info "It is advised to run 'minikube tunnel' first."}

      ip=$(get-istio-ingress-lb-port)
      domain=$ip.nip.io

      ${pkgs.lib.log.important "Generating certs"}
      tmpfile=$(mktemp -d)

      (cd $tmpfile && ${pkgs.mkcert}/bin/mkcert \
        autogenerated \
        express-app.dev-functions.$domain \
        bitbucket-message-dumper.dev-functions.$domain \
        localhost)
      
      ${pkgs.kubectl}/bin/kubectl create --namespace istio-system secret tls istio-ingressgateway-certs \
        --key $tmpfile/autogenerated+3-key.pem \
        --cert $tmpfile/autogenerated+3.pem

      ${pkgs.kubectl}/bin/kubectl patch \
        cm config-domain -n knative-serving \
        -p '{"data":{"'"$domain"'":"","nip.io":null}}'
    '')
  ];

  kubernetes.patches = [
  ];


  kubernetes.network-mesh = {
    enable = true;

    helm = {
      gateways = {
        istio-ingressgateway = {
          type = "LoadBalancer";
        };
      };

      global = {
        k8sIngress.gatewayName = "ingressgateway";
      };
    };
  };
}